### ISSUE TITLE
Allowing Continued Development Through VT GitHub Organization

### ISSUE THREAD

**Issue by mpetracca26** [amhokies/Slapdash-Server#42]
What do you guys think about adding this repo and its Android counterpart to the VT GitHub Organization, so that it could get more exposure and other VT students could continue to develop it?

**Comment by amhokies** [comment]
Yeah, that sounds cool. I've already added one of my own repositories though so I'm not sure if I should wait or something before adding this one, as well as the Android Repo.

**Comment by mpetracca26** [comment]
There's no limit to how many repositories you can add.  So add away!  Just make sure that you switch the Android repo from Private to Public before adding it.  The bot I made will automatically make whoever adds the repo, through the [virginiatech.github.io](https://virginiatech.github.io) website, Admin, but that user will then have to manually add the rest of the collaborators to the forked repo.

**Comment by amhokies** [comment]
Alright, I added them both.

**Comment by mpetracca26** [comment]
awesome, I just approved both of them!  Just remember to add us back as collaborators when you get the chance. :)
